---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: workshop-main
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.workshop.main
  name: mysql-secret
data:
  mysql-password: cmVkaGF0
type: Opaque
