---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: workshop-main
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: workshop-main@sha256:68bd3e2fa913840576d398711974326a3185df192ccb6270c3156cfcb7eb0519
        namespace: service
      name: latest
