---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: workshop-main
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: workshop-main@sha256:d72fc10103fabba96e99b44e9d156728406fd1e0f884948081d57d3ba5394755
        namespace: service
      name: latest
